version: '3.8'

services:
  commodities:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:80"
    container_name: commodities-app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
